package project.framework.gui.defaults.dialogs;

import javax.swing.*;

public class GenericJDialog extends javax.swing.JDialog {
    public String content;

    public GenericJDialog(JFrame parentFrame, String content) {
        super(parentFrame);

        // This code is automatically generated by Visual Cafe when you add
        // components to the visual environment. It instantiates and initializes
        // the components. To modify the code, only use code syntax that matches
        // what Visual Cafe can generate, or Visual Cafe may be unable to back
        // parses  your Java file into its visual envirenment.
        //{{ INIT_CONTROLS
        getContentPane().setLayout(null);
        setSize(600, 367);
        setVisible(false);
        getContentPane().add(JScrollPane1);
        JScrollPane1.setBounds(24, 24, 358, 240);
        JScrollPane1.getViewport().add(JTextArea);
        JTextArea.setBounds(0, 0, 500, 237);
        JButton_OK.setText("OK");
        JButton_OK.setActionCommand("OK");
        getContentPane().add(JButton_OK);
        JButton_OK.setBounds(156, 276, 96, 24);

        this.content = content;
        JTextArea.setText(content);
        //}}

        bindActionListenersToJButtons();

    }

    public void bindActionListenersToJButtons() {
        //{{REGISTER_LISTENERS
        JButton_OK.addActionListener(e -> {
            dispose();
        });
        //}}
    }


    //{{DECLARE_CONTROLS
    javax.swing.JScrollPane JScrollPane1 = new javax.swing.JScrollPane();

    javax.swing.JTextArea JTextArea = new javax.swing.JTextArea();

    javax.swing.JButton JButton_OK = new javax.swing.JButton();
    //}}

}
