package project.framework.gui.defaults.dialogs;


import project.framework.gui.defaults.modal.OrgAFormInputModal;

import javax.swing.*;

public class GenericJDialog_AddOrganizationAcc extends javax.swing.JDialog {
    private JFrame parentframe;

    private OrgAFormInputModal orgAFormInputModal;
    boolean newaccount;

    public GenericJDialog_AddOrganizationAcc(JFrame parentFrame, String dialogTitle) {
        super(parentFrame);
        parentframe = parentFrame;

        // This code is automatically generated by Visual Cafe when you add
        // components to the visual environment. It instantiates and initializes
        // the components. To modify the code, only use code syntax that matches
        // what Visual Cafe can generate, or Visual Cafe may be unable to back
        // parse  your Java file into its visual envirenment.
        //{{ INIT_CONTROLS
        setTitle(dialogTitle);
        setModal(true);
        getContentPane().setLayout(null);
        setSize(298, 339);
        setVisible(false);

        JLabel1.setText("Name");
        getContentPane().add(JLabel1);
        JLabel1.setForeground(java.awt.Color.black);
        JLabel1.setBounds(12, 96, 48, 24);
        JLabel2.setText("Street");
        getContentPane().add(JLabel2);
        JLabel2.setForeground(java.awt.Color.black);
        JLabel2.setBounds(12, 120, 48, 24);
        JLabel3.setText("City");
        getContentPane().add(JLabel3);
        JLabel3.setForeground(java.awt.Color.black);
        JLabel3.setBounds(12, 144, 48, 24);
        JLabel4.setText("State");
        getContentPane().add(JLabel4);
        JLabel4.setForeground(java.awt.Color.black);
        JLabel4.setBounds(12, 168, 48, 24);
        JLabel5.setText("Zip");
        getContentPane().add(JLabel5);
        JLabel5.setForeground(java.awt.Color.black);
        JLabel5.setBounds(12, 192, 48, 24);
        JLabel6.setText("No of employees");
        getContentPane().add(JLabel6);
        JLabel6.setForeground(java.awt.Color.black);
        JLabel6.setBounds(12, 216, 96, 24);
        JLabel7.setText("Email");
        getContentPane().add(JLabel7);
        JLabel7.setForeground(java.awt.Color.black);
        JLabel7.setBounds(12, 240, 48, 24);
        getContentPane().add(JTextField_NAME);
        JTextField_NAME.setBounds(120, 96, 156, 20);
        getContentPane().add(JTextField_CT);
        JTextField_CT.setBounds(120, 144, 156, 20);
        getContentPane().add(JTextField_ST);
        JTextField_ST.setBounds(120, 168, 156, 20);
        getContentPane().add(JTextField_STR);
        JTextField_STR.setBounds(120, 120, 156, 20);
        getContentPane().add(JTextField_ZIP);
        JTextField_ZIP.setBounds(120, 192, 156, 20);
        getContentPane().add(JTextField_NoOfEmp);
        JTextField_NoOfEmp.setBounds(120, 216, 156, 20);
        getContentPane().add(JTextField_EM);
        JTextField_EM.setBounds(120, 240, 156, 20);
        JButton_OK.setText("OK");
        JButton_OK.setActionCommand("OK");
        getContentPane().add(JButton_OK);
        JButton_OK.setBounds(48, 276, 84, 24);
        JButton_Calcel.setText("Cancel");
        JButton_Calcel.setActionCommand("Cancel");
        getContentPane().add(JButton_Calcel);
        JButton_Calcel.setBounds(156, 276, 84, 24);
        JLabel8.setText("Acc Nr");
        getContentPane().add(JLabel8);
        JLabel8.setForeground(java.awt.Color.black);
        JLabel8.setBounds(12, 72, 48, 24);
        getContentPane().add(JTextField_ACNR);
        JTextField_ACNR.setBounds(120, 72, 156, 20);
        //}}

        bindActionListenersToJButtons();
    }

    public void bindActionListenersToJButtons() {
        //{{REGISTER_LISTENERS
        JButton_OK.addActionListener(e -> {
            this.getOrgAFormInputModal();
            newaccount = true;
            dispose();
        });
        JButton_Calcel.addActionListener(e -> {
            dispose();
        });
        //}}
    }

    javax.swing.JLabel JLabel1 = new javax.swing.JLabel();
    javax.swing.JLabel JLabel2 = new javax.swing.JLabel();
    javax.swing.JLabel JLabel3 = new javax.swing.JLabel();
    javax.swing.JLabel JLabel4 = new javax.swing.JLabel();
    javax.swing.JLabel JLabel5 = new javax.swing.JLabel();
    javax.swing.JLabel JLabel6 = new javax.swing.JLabel();
    javax.swing.JLabel JLabel7 = new javax.swing.JLabel();
    javax.swing.JTextField JTextField_NAME = new javax.swing.JTextField();
    javax.swing.JTextField JTextField_CT = new javax.swing.JTextField();
    javax.swing.JTextField JTextField_ST = new javax.swing.JTextField();
    javax.swing.JTextField JTextField_STR = new javax.swing.JTextField();
    javax.swing.JTextField JTextField_ZIP = new javax.swing.JTextField();
    javax.swing.JTextField JTextField_NoOfEmp = new javax.swing.JTextField();
    javax.swing.JTextField JTextField_EM = new javax.swing.JTextField();
    javax.swing.JButton JButton_OK = new javax.swing.JButton();
    javax.swing.JButton JButton_Calcel = new javax.swing.JButton();
    javax.swing.JLabel JLabel8 = new javax.swing.JLabel();
    javax.swing.JTextField JTextField_ACNR = new javax.swing.JTextField();
    //}}


    public OrgAFormInputModal getOrgAFormInputModal() {
        OrgAFormInputModal orgAFormInputModal = new OrgAFormInputModal();
        orgAFormInputModal.setAccountnr(JTextField_ACNR.getText());
        orgAFormInputModal.setClientName(JTextField_NAME.getText());
        orgAFormInputModal.setStreet(JTextField_STR.getText());
        orgAFormInputModal.setCity(JTextField_CT.getText());
        orgAFormInputModal.setZip(JTextField_ZIP.getText());
        orgAFormInputModal.setState(JTextField_ST.getText());
        orgAFormInputModal.setEmail(JTextField_EM.getText());
        return orgAFormInputModal;
    }

    public boolean isNewaccount() {
        return newaccount;
    }

    public void setNewaccount(boolean newaccount) {
        this.newaccount = newaccount;
    }

    public JButton getJButton_OK() {
        return JButton_OK;
    }
}